export const SUBSCRIPTION_SERVICES: SubscriptionService[] = [
    {
        service_name: "Netflix",
        name: "넷플릭스",
        category: "OTT",
        kakaoLogoUrl: "/logos-kakao/netflix.png",
        logoUrl: "/logos-webp/netflix.webp",
        site_url: "https://www.netflix.com",
        plans: [
            { id: "nf-ad", name: "광고형 스탠다드", price: 7000 },
            { id: "nf-st", name: "스탠다드", price: 13500 },
            { id: "nf-pr", name: "프리미엄", price: 17000 },
            { id: "nf-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Youtube_premium",
        name: "유튜브 프리미엄",
        category: "OTT",
        kakaoLogoUrl: "/logos-kakao/youtubepremium.png",
        logoUrl: "/logos-webp/youtubepremium.webp",
        site_url: "https://www.youtube.com/premium",
        plans: [
            { id: "yt-pl", name: "프리미엄 라이트", price: 8500 },
            { id: "yt-pl(ios)", name: "프리미엄 라이트(ios)", price: 10900 },
            { id: "yt-pr", name: "프리미엄", price: 14900 },
            { id: "yt-pr(ios)", name: "프리미엄(ios)", price: 19500 },
            { id: "yt-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Tving",
        name: "티빙",
        category: "OTT",
        kakaoLogoUrl: "/logos-kakao/tving.png",
        logoUrl: "/logos-webp/tving.webp",
        site_url: "https://www.tving.com",
        plans: [
            { id: "tv-ad", name: "광고형 스탠다드", price: 5500 },
            { id: "tv-ba", name: "베이직", price: 9500 },
            { id: "tv-st", name: "스탠다드", price: 13500 },
            { id: "tv-pr", name: "프리미엄", price: 17000 },
            { id: "tv-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Disney_plus",
        name: "디즈니 플러스",
        category: "OTT",
        kakaoLogoUrl: "/logos-kakao/disney.png",
        logoUrl: "/logos-webp/disney.webp",
        site_url: "https://www.disneyplus.com",
        plans: [
            { id: "dp-st", name: "스탠다드", price: 9900 },
            { id: "dp-pr", name: "프리미엄", price: 13900 },
            { id: "dp-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Wavve",
        name: "웨이브",
        category: "OTT",
        kakaoLogoUrl: "/logos-kakao/wavve.png",
        logoUrl: "/logos-webp/wavve.webp",
        site_url: "https://www.wavve.com",
        plans: [
            { id: "wv-ba", name: "베이직", price: 7900 },
            { id: "wv-st", name: "스탠다드", price: 10900 },
            { id: "wv-pr", name: "프리미엄", price: 13900 },
            { id: "wv-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Watcha",
        name: "왓챠",
        category: "OTT",
        kakaoLogoUrl: "/logos-kakao/watcha.png",
        logoUrl: "/logos-webp/watcha.webp",
        site_url: "https://watcha.com",
        plans: [
            { id: "wc-ba", name: "베이직", price: 7900 },
            { id: "wc-pr", name: "프리미엄", price: 12900 },
            { id: "wc-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Coupang_play",
        name: "쿠팡플레이",
        category: "OTT",
        kakaoLogoUrl: "/logos-kakao/coupangplay.png",
        logoUrl: "/logos-webp/coupangplay.webp",
        site_url: "https://www.coupangplay.com",
        plans: [
            { id: "cp-wow", name: "와우 멤버십 포함", price: 7890 },
            { id: "cp-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Melon",
        name: "멜론",
        category: "MUSIC",
        kakaoLogoUrl: "/logos-kakao/melon.png",
        logoUrl: "/logos-webp/melon.webp",
        site_url: "https://www.melon.com",
        plans: [
            { id: "ml-ms", name: "모바일 스트리밍 클럽 정기결제", price: 7590 },
            { id: "ml-st", name: "스트리밍 클럽 정기결제", price: 8690 },
            { id: "ml-stk", name: "스트리밍 티켓 30일", price: 9790 },
            { id: "ml-pl", name: "스트리밍 플러스 정기결제", price: 11990 },
            { id: "ml-tk", name: "스트리밍 플러스 티켓", price: 12540 },
            { id: "ml-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Spotify",
        name: "스포티파이",
        category: "MUSIC",
        kakaoLogoUrl: "/logos-kakao/spotify.png",
        logoUrl: "/logos-webp/spotify.webp",
        site_url: "https://www.spotify.com",
        plans: [
            { id: "sp-sd", name: "학생", price: 6000 },
            { id: "sp-bg", name: "베이직", price: 7900 },
            { id: "sp-in", name: "개인 (Individual)", price: 10900 },
            { id: "sp-du", name: "듀오 (Duo)", price: 16350 },
            { id: "sp-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Youtube_music",
        name: "유튜브 뮤직",
        category: "MUSIC",
        kakaoLogoUrl: "/logos-kakao/youtubemusic.png",
        logoUrl: "/logos-webp/youtubemusic.webp",
        site_url: "https://music.youtube.com",
        plans: [
            { id: "ym-pr", name: "개인", price: 11900 },
            { id: "ym-pr(ios)", name: "개인(ios)", price: 14900 },
            { id: "ym-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Apple_music",
        name: "애플 뮤직",
        category: "MUSIC",
        kakaoLogoUrl: "/logos-kakao/applemusic.png",
        logoUrl: "/logos-webp/applemusic.webp",
        site_url: "https://www.apple.com/apple-music/",
        plans: [
            { id: "am-in", name: "개인", price: 8900 },
            { id: "am-fa", name: "가족", price: 13500 },
            { id: "am-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Genie",
        name: "지니",
        category: "MUSIC",
        kakaoLogoUrl: "/logos-kakao/genie.png",
        logoUrl:"/logos-webp/genie.webp",
        site_url: "https://www.genie.co.kr",
        plans: [
            { id: "gn-sst", name: "스마트 음악감상", price: 7900 },
            { id: "gn-st", name: "음악감상", price: 8400 },
            { id: "gn-dsst", name: "데이터 세이프 음악감상", price: 10900 },
            { id: "gn-hst", name: "초고음질 음악감상", price: 14000 },
            { id: "gn-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Bugs",
        name: "벅스",
        category: "MUSIC",
        kakaoLogoUrl: "/logos-kakao/bugs.png",
        logoUrl: "/logos-webp/bugs.webp",
        site_url: "https://music.bugs.co.kr",
        plans: [
            { id: "bg-cst", name: "벅스 크루 할인", price: 5940 },
            { id: "bg-yst", name: "벅스 1년 할인", price: 7386 },
            { id: "bg-mst", name: "모바일 무제한 듣기", price: 7590 },
            { id: "bg-st", name: "무제한 듣기", price: 8690 },
            { id: "bg-offst", name: "오프라인 무제한 듣기", price: 11990 },
            {
                id: "bg-offpst",
                name: "프리미엄 오프라인 무제한 듣기",
                price: 17600,
            },
            { id: "bg-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Coupang_eats",
        name: "쿠팡 이츠",
        category: "FOOD",
        kakaoLogoUrl: "/logos-kakao/coupangeats.png",
        logoUrl: "/logos-webp/coupangeats.webp",
        site_url: "https://www.coupangeats.com",
        plans: [
            { id: "cw-mo", name: "월간 멤버십", price: 7890 },
            { id: "cw-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Coupang_wow",
        name: "쿠팡 와우",
        category: "SHOPPING",
        kakaoLogoUrl: "/logos-kakao/coupangwow.png",
        logoUrl: "/logos-webp/coupangwow.webp",
        site_url: "https://www.coupang.com",
        plans: [
            { id: "cw-mo", name: "월간 멤버십", price: 7890 },
            { id: "cw-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Naver_plus",
        name: "네이버 플러스 멤버십",
        category: "SHOPPING",
        kakaoLogoUrl: "/logos-kakao/navermembership.png",
        logoUrl:"/logos-webp/navermembership.webp",
        site_url: "https://nid.naver.com/membership/join",
        plans: [
            { id: "np-mo", name: "월간 이용권", price: 4900 },
            { id: "np-ye", name: "연간 이용권 (월 평균)", price: 3900 },
            { id: "np-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Baemin_club",
        name: "배민클럽",
        category: "FOOD",
        kakaoLogoUrl: "/logos-kakao/bamin.png",
        logoUrl: "/logos-webp/bamin.webp",
        site_url: "https://www.baemin.com",
        plans: [
            { id: "bm-pmo", name: "월간 이용권(프로모션가)", price: 1990 },
            { id: "bm-mo", name: "월간 이용권", price: 3900 },
            { id: "bm-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Kurly_lovers",
        name: "컬리 러버스",
        category: "SHOPPING",
        kakaoLogoUrl: "/logos-kakao/kurly.png",
        logoUrl: "/logos-webp/kurly.webp",
        site_url: "https://www.kurly.com",
        plans: [
            { id: "kl-pa", name: "컬리패스", price: 4500 },
            { id: "kl-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Shinsegae_universe",
        name: "신세계 유니버스",
        category: "SHOPPING",
        kakaoLogoUrl: "/logos-kakao/shinsegae.png",
        logoUrl: "/logos-webp/shinsegae.webp",
        site_url: "https://www.shinsegae-universe.com",
        plans: [
            { id: "su-ye", name: "연간 멤버십 (연 3만원)", price: 2500 },
            { id: "su-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Chatgpt",
        name: "ChatGPT",
        category: "AI",
        kakaoLogoUrl: "/logos-kakao/chatgpt.png",
        logoUrl: "/logos-webp/chatgpt.webp",
        site_url: "https://chat.openai.com",
        plans: [
            { id: "gpt-go", name: "Go (월 $8)", price: 11200 },
            { id: "gpt-plus", name: "Plus (월 $20)", price: 28000 },
            { id: "gpt-pro", name: "Pro (월 $200)", price: 280000 },
            { id: "gpt-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Gemini",
        name: "Gemini",
        category: "AI",
        kakaoLogoUrl: "/logos-kakao/gemini.png",
        logoUrl:"/logos-webp/gemini.webp",
        site_url: "https://gemini.google.com",
        plans: [
            { id: "gmn-free", name: "Gemini (Free)", price: 0 },
            {
                id: "gmn-adv",
                name: "Gemini Advanced (Ultra 1.0 + 2TB)",
                price: 29000,
            },
            { id: "gmn-biz", name: "Gemini Business (월 $20)", price: 28000 },
            {
                id: "gmn-ent",
                name: "Gemini Enterprise (Ultra 포함 / 월 $30)",
                price: 42000,
            },
            { id: "gmn-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Claude",
        name: "Claude",
        category: "AI",
        kakaoLogoUrl: "/logos-kakao/claude.png",
        logoUrl: "/logos-webp/claude.webp",
        site_url: "https://claude.ai",
        plans: [
            { id: "cld-free", name: "Free", price: 0 },
            { id: "cld-pro", name: "Pro (월 $20)", price: 28000 },
            { id: "cld-team", name: "Team (월 $30)", price: 42000 },
            { id: "cld-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
    {
        service_name: "Cursor",
        name: "Cursor",
        category: "AI",
        kakaoLogoUrl: "/logos-kakao/cursor.png",
        logoUrl: "/logos-webp/cursor.webp",
        site_url: "https://www.cursor.com",
        plans: [
            { id: "csr-hobby", name: "Hobby (Free)", price: 0 },
            { id: "csr-pro", name: "Pro (월 $20)", price: 28000 },
            { id: "csr-biz", name: "Business (월 $40)", price: 56000 },
            { id: "csr-custom", name: "기타 (직접 입력)", price: 0 },
        ],
    },
];
